---
title: "Projet de session – POL-6078"
author: "Thomas Laframboise"
date: "2025-12-13"
output: html_document
---


Outils numériques en sciences sociales
POL-6078


Travail de recherche
« Quel est l’impact des variations des dépenses militaires d’un pays sur ses importations d’armes en 2024? »



Travail présenté à
Adrien Cloutier



Par
Thomas Laframboise (536784120) 






Université Laval
Automne 2025
12 décembre 2025

## 1. Question de recherche et hypothèse
### 1.1 La question de recherche
Dans le cadre de ce projet de recherche, il est question du domaine du commerce international de l’armement, plus spécifiquement sur l’influence de l’augmentation des dépenses militaires des États sur leurs variations d’importations d’armement. Ce sujet m’a interpellé à la suite des annonces d’augmentation des dépenses militaires du gouvernement canadien à l’automne 2025. Cela m’a amené à me questionner sur l’influence qu’une augmentation des dépenses militaires peuvent avoir sur le PIB d’un pays et, par la même occasion, quelle proportion de ses dépenses vont à l’étranger. Donc, ce texte cherche à répondre à la question suivante : quel est l’impact des variations des dépenses militaires d’un pays sur ses importations d’armes?

### 1.2 Revue rapide de la littérature
Selon plusieurs sources, lorsqu’un État augmente ses dépenses militaires, cela conduit généralement à l’augmentation des importations d’armement par ce dernier (Smith & Tasiran, 2005) (Chary, 2024). La littérature tend aussi à montrer que plus les dépenses militaires augmentent et plus la part des importations d’armes diminue. Cela s’explique par le fait que l’augmentation des dépenses militaires stimule le développement de l’industrie local permettant par la même occasion de diminuer la dépendance aux importations (Smith & Tasiran, 2005) (Smith, & Tasiran, 2010). On observe aussi que le niveau de développement de l’industrie militaire d’un pays est inversement proportionnel à celui de l’importation d’armement, puisque les états ont tendance à n’importer que ce qu’ils ne produisent pas pour éviter une dépendance stratégique. Alors, plus on produit de produits différents et moins on importe (Blum, 2019). Bref, les études semblent conclure que l’augmentation des dépenses militaires des états fait augmenter leur importation d’armement spécialement pour les pays avec une industrie militaire peu développés.

### 1.3 L’hypothèse
Ainsi, la revue de littérature nous permet de dériver l’hypothèse suivante : l’augmentation des dépenses militaires d’un État influence la hausse des importations d’armement. Cela est justifier par le fait que plus il y a de dépenses et plus il y a de demandes de matériel ainsi que l’élasticité de la demande en importation par rapport aux dépenses militaires est positive (Blum, 2019) (Smith & Tasiran, 2005). 



### 1.4 Outils numériques utilisés pour cette étape
Au cours de la revue de littérature, j’ai utilisé Consensus, Google Scholar et NotebookLM. D’abord j’ai utilisé Consensus afin d’avoir directement plusieurs sources directement sur mon sujet de recherche. Je lui ai écrit sur quel sujet je cherchais des sources et j’ai pu ressortir rapidement les plus pertinentes. Ensuite, j’ai utilisé Google Scholar pour vérifier qu’il n’y a pas d’autres études pertinentes oubliées et pour avoir accès au PDF des sources que j’ai gardé de Consensus. Finalement, dans l’ensemble de la recherche, j’ai utilisé NotebookLM pour alléger mes lectures et pour vérifier les conclusions de Consensus.

## 2. Collecte de données
### 2.1 Description des sources de données
Pour effectuer la collecte de données, je me suis basé sur deux sources de données en ligne : SIPRI Arms Transfers Database et SIPRI Military Expenditure. Ces choix de base de données sont justifiés par le fait que trois études de la revue de littérature se basent sur ces mêmes bases de données. Ces bases de données sont issues d’un institut international indépendant qui crée les bases de données pour la recherche.La base de données SIPRI Arms Transfers Database fournit des données d’importation d’armes par pays, de 1950 à 2025, mais j’utilise seulement 2024 et un indicateur standardisé d’importation nommé Trend Indicator Value (TIV). Ensuite, la base de données SIPRI Military Expenditure fournit les dépenses militaires en dollar américain de 1949 à 2024, où j’utilise seulement 2024. Elles sont pertinentes, puisqu’elles sont faites par la même institution, ce qui les rend facilement compatibles et elles permettent d’étudier simultanément les dépenses militaires et les importations d’armement.

### 2.2 Méthode de collecte des données
La méthode de collecte de données consistait simplement à aller télécharger les deux fichiers CSV sur le site du SIPRI. Ensuite, je les ai importés dans Rstudio en m’assurant de nettoyer les données afin que mon code ignore les lignes descriptives des tableaux. J’ai choisi d’analyser les données de 2024, puisque c’est l’année la plus récente disponible dans les bases de données et c’est une année qui n’a pas été prise en considération dans les années précédentes.
Puisque les fichiers comportaient plusieurs lignes descriptives, j’ai utilisé la fonction read_csv() afin d’importer les données sur les importations d’armes. J’ai utilisé la fonction read_delim(delim = ";") et skip = 5 pour importer les données sur les dépenses militaires, puisque le dossier utilisait des virgules comme séparateur. J’ai aussi renommé des colonnes pour harmoniser les données et converties en numérique les données du fichier sur les dépenses militaires. J’ai seulement utilisé les noms des pays et la colonne de 2024 dans chaque base de données. J’ai aussi enlevé les valeurs manquantes pour le rendre plus lisible et comparable.
Finalement, j’ai utilisé la fonction inner_join() pour fusionner mes bases de données sur la variable pays pour seulement garder ceux présents dans les deux bases de données. Le tableau final regroupe 100 pays avec les variables des deux fichiers que j’utilise pour faire mes graphiques et ma régression.

### 2.3 Justification de l'utilisation des outils numériques
J’ai choisi d’utiliser Rstudio, puisque c’est le logiciel de traitement de données que je connais le mieux, alors son utilisation était une évidence pour moi. Dans mon code, j’ai utilisé le package readr afin d’importer les fichiers de SIPRI, le package dplyr pour simplifier la manipulation des données et ggplot2 pour l’affichage de mes résultats.

## 3. Analyse et visualisation des données
Toujours avec Rstudio, j’ai utilisé les données précédemment décrites pour faire un graphique ainsi qu’une régression linéaire simple afin d’analyser l’impact des dépenses militaires sur les importations d’armes. Le graphique, où les dépenses militaires sont sur l’axe des x et les importations sur l’axe des y, permet de voir une relation positive qui montre que les pays qui augmentent leurs dépenses militaires ont tendance à augmenter leur importation d’armement aussi. Il montre aussi une forte dispersion des points et que certains pays qui sont très dépensiers importent peu d’arme, ce qui rejoins la littérature sur le point de l’industrie militaire très développé.
Cependant, malgré une relation positive et significative avec une valeur p de 0.007752, la relation reste plutôt faible. La régression nous permet de confirmer statistiquement le lien entre l’augmentation des dépenses militaires et l’augmentation des importations d’armement. Mais, la valeur R² de 0,07 indique visiblement que les dépenses militaires n’expliquent qu’une petite partie des observations entre chaque pays et que d’autres facteurs influencent aussi les importations d’armes. Bref, les dépenses militaires sont bien liées aux importations, mais ce lien est modéré et probablement influencé par d’autres facteurs, ce qui rejoint les résultats de la revue de littérature.

## 4. Discussion
Dans le cadre de ce projet, j’ai pris soin de privilégié des outils et des sources libres, dont R, Rstudio et les bases de données de SIPRI. Le facteur principal qui a guidé mon choix est l’accessibilité de ces outils. En effet, le fait qu’ils soient gratuits rend la décision facile à prendre. Le second est la flexibilité. En effet, je savais que peu importe où allait mon analyse, j’allais trouver facilement un moyen de l’appliquer sur R et de trouver des packages répondant à mes besoins. Le troisième facteur de décision est la popularité dans mon domaine. En effet, puisque je risque de devoir réutiliser le code R et Rstudio au cours de ma carrière et de mon parcours universitaire, je préférais renforcer mes compétences dans ces derniers pour m’améliorer. Finalement, le dernier facteur de décision était, et non le moindre, le côté libre de ces outils. En effet, je ne connaissais pas ce monde et cette culture avant le cours d’outils numérique et j’ai rapidement intégré ses valeurs. Je ne suis pas le meilleur en informatique, ni le plus débrouillard, ce qui me limite dans l'utilisation des logiciels ouverts, mais maintenant, lorsque l’option s’offre à moi, je n’hésite plus à choisir celle-ci qui est, selon moi, plus éthique.Bref, l’utilisation de RStudio, un logiciel libre et source ouvert, a permis d’assurer la transparence, la reproductibilité des analyses et l’intégration complète entre le texte, les données et les visualisations dans ce travail.

## 5. Conclusion
Pour conclure, les résultats de l’analyse faite grâce aux bases de données du Stockholm International Peace Research Institute et du logiciel Rstudio révèlent une relation positive, mais limitée entre l’augmentation des dépenses militaires d’un État et l’augmentation de ses importations d’armement. Cela insinue que d’autres facteurs entrent en jeu, comme le développement de l’industrie militaire du pays lui-même si on se fie à la littérature. Ainsi, cela confirme partiellement l’hypothèse selon laquelle l’augmentation des dépenses militaires d’un État influence l’augmentation de ses importations d’armement et renforce l’importance des autres facteurs. Bref, ce projet renforce la valeur de l’approche quantitative simple afin d’analyser le commerce international des armes. Des recherches futures pourraient intégrer des variables institutionnelles et industrielles dans l’analyses.


## Bibliographie
Blum, J. (2019). Arms production, national defense spending and arms trade: Examining supply and demand. European Journal of Political Economy, 60, 101814.
Chary, S. (2024). The nexus between arms imports, military expenditures and economic growth of the top arms importers in the world: a pooled mean group approach. Journal of economic studies, 51(4), 808-822.
Smith, R. P., & Tasiran, A. (2005). The demand for arms imports. Journal of Peace Research, 42(2), 167-181.
Smith, R. P., & Tasiran, A. (2010). Random coefficients models of arms imports. Economic Modelling, 27(6), 1522-1528.


